#!/bin/bash

# tag manipulation fields from http://www.mcternan.co.uk/aifffffs/

TMPFILE=$(mktemp /tmp/XXXXXX)
metaflac --list --block-type=VORBIS_COMMENT "${1}" > $TMPFILE
for TAG in TITLE ARTIST ALBUM DISCNUMBER DISCTOTAL DATE TRACKNUMBER TRACKTOTAL COMPILATION GROUPING LICENSE COMMENT; do
	eval $TAG=\`grep ${TAG}= $TMPFILE\|sed s/.\*${TAG}=//\`
done
rm $TMPFILE

PICFILE=$(mktemp /tmp/XXXXXX)
metaflac --export-picture-to=${PICFILE} "${1}"

PICDATA=$(mktemp /tmp/XXXXXX)
metaflac --list --block-type=PICTURE "${1}" > $PICDATA
PICTYPE=`grep 'MIME type: ' $PICDATA|sed s/.*'MIME type: '//`
PICDESC=`grep 'description: ' $PICDATA|sed s/.*'description: '//`
rm $PICDATA

EYED3_VER=$(eyeD3 --version 2>&1 | awk '$1 ~ "eyeD3" { print $2 }')
if [ "${EYED3_VER}" != "0.6.18" ] ; then
  EYED3_ARGS="--text-frame "
else
  EYED3_ARGS="--set-text-frame="
fi

WAVFILE=$(mktemp /tmp/XXXXXX)
flac -d "${1}" -s -f -o ${WAVFILE}

OUTFILE=`echo ${1}|sed s/flac/mp3/I`

lame -V2 --vbr-new -b 112 -B 320 -S --noreplaygain --add-id3v2 --id3v2-only --tt "${TITLE}" --ta "${ARTIST}" --tl "${ALBUM}" --ty "${DATE}" --tn ${TRACKNUMBER}/${TRACKTOTAL} $WAVFILE "${OUTFILE}"

rm $WAVFILE

case ${PICTYPE} in
  image/jpeg)
    mv "${PICFILE}" "${PICFILE}.jpg"
    PICFILE="${PICFILE}.jpg"
  ;;
  *)
  ;;
esac

eyeD3 --add-image=${PICFILE}:FRONT_COVER "${OUTFILE}" > /dev/null

rm $PICFILE

if [ ! -z "${DISCTOTAL}" ] ; then
  DISCNUMBER="${DISCNUMBER}/${DISCTOTAL}"
fi

if [ EYED3_VER != "0.6.18" ] ; then
  eyeD3 ${EYED3_ARGS}TPOS:"${DISCNUMBER}" "${OUTFILE}" > /dev/null
else
  eyeD3 --no-zero-padding ${EYED3_ARGS}TPOS:"${DISCNUMBER}" "${OUTFILE}" > /dev/null
fi

if [ ! -z "${COMPILATION}" ] ; then
  if [ "${COMPILATION}" -eq "1" ]; then
    eyeD3 ${EYED3_ARGS}TCMP:1 "${OUTFILE}" > /dev/null
  fi
fi

if [ ! -z "${GROUPING}" ]; then
  eyeD3 ${EYED3_ARGS}TIT1:"${GROUPING}" "${OUTFILE}" > /dev/null
fi

if [ ! -z "${LICENSE}" ] ; then
  # weird bug in my easytag - URL got mapped to license - but we want GEN2 in the comment field anyway
  if [[ "${LICENSE}" =~ "GEN2" ]] ; then
    COMMENT="GEN2_SRC ${COMMENT}"
  fi
fi

COMMENT="FLAC2MP3_1.1 ${COMMENT}"

if [ EYED3_VER != "0.6.18" ] ; then
  eyeD3 --comment "${COMMENT}" "${OUTFILE}" > /dev/null
else
  eyeD3 --comment "eng:'':${COMMENT}" "${OUTFILE}" > /dev/null
fi

vbrfix "${OUTFILE}" "${OUTFILE}" > /dev/null
